services:
  tasks-api:
    container_name: tasks-api
    build:
      context: ./tasks_api
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./tasks_api/app:/app
    env_file:
      - ./tasks_api/.env
    depends_on:
      - tasks-db

  tasks-db:
    container_name: tasks-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./tasks_api/.env
    ports:
      - "5432:5432"
    volumes:
      - tasks_db_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  tasks_db_data:

